@ImageProcessingService_HostAddress = http://localhost:5037
        
POST {{ImageProcessingService_HostAddress}}/api/auth
Accept: application/json

### Register Admin User

POST {{ImageProcessingService_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "userName": "johndoe",
  "password": "StrongPassword123!",
  "email": "johndoe@example.com",
  "phoneNumber": "1234567890",
  "roles": ["Administrator"]
}

### Register User 
POST {{ImageProcessingService_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "userName": "johndoez",
  "password": "StrongPassword123!",
  "email": "johndoez@example.com",
  "phoneNumber": "1234567890",
  "roles": ["User"]
}


### POST LOGIN  --- Admin | Manager 
POST {{ImageProcessingService_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "StrongPassword123!"
}


### POST images
POST {{ImageProcessingService_HostAddress}}/api/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary12345

------WebKitFormBoundary12345
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

< C:\Users\DaMagic\Pictures\NissanNitro127.jpg
------WebKitFormBoundary12345--

### Get image by ID
@IdImage = 2

GET {{ImageProcessingService_HostAddress}}/api/images/{{IdImage}}
Accept: application/json

@Token = "Bearer {{}}

### Get all images
GET {{ImageProcessingService_HostAddress}}/api/images
Authorization:  Bearer {{Token}}

### Delete User By Id 
@IdUser = "InvalidUserId"
DELETE {{ImageProcessingService_HostAddress}}/api/auth/{{IdUser}}